version: '3'
services:
  db_postgres:
    container_name: db_postgres
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: batatachips
    ports:
      - "5432:5432"
    volumes:
      - "/tmp/database:/var/lib/postgresql/data"
      - "./case_steps/passo1:/docker-entrypoint-initdb.d"
    networks:
      - rede_casebravium
  python_container:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_postgres
    volumes:
      - "./case_steps:/case_steps"
    networks:
      - rede_casebravium
networks:
  rede_casebravium:
